import{a as f,S as h,i as v}from"./assets/vendor-da186403.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const b="42527051-ab9ea8069b5c425aa0269f2a2",o={image_type:"photo",orientation:"horizontal",safesearch:!0},_=f.create({baseURL:"https://pixabay.com/api",headers:{Accept:"application/json"}});async function L(a){return(await _.get(`?key=${b}&q=${encodeURIComponent(a)}`,{params:o})).data}const S=document.querySelector(".gallery"),I=new h(".gallery .gallery-link",{className:"gallery-link",closeText:['<i class="fa fa-times">&#10006;</i>'],navText:['<i class="fa fa-angle-left">&lt;</i>','<i class="fa fa-angle-right">&gt;</i>'],captionsData:"alt",captionDelay:250}),d=a=>{const t=a.map(({webformatURL:n,largeImageURL:i,tags:e,likes:s,views:l,comments:u,downloads:m})=>`<a class="gallery-link" href="${i}">
                          <img
                            class="gallery-image"
                            src="${n}"
                            alt="${e}"
                          />
                          <figcaption class="gallery__figcaption">
                             <div class="gallery__caption">Likes: <span>${s}</span></div>
                             <div class="gallery__caption">Views: <span>${l}</span></div>
                             <div class="gallery__caption">Comments: <span>${u}</span></div>
                             <div class="gallery__caption">Downloads: <span>${m}</span></div>
                          </figcaption>
                        </a>`).join("");S.insertAdjacentHTML("beforeend",t),I.refresh()},q=document.querySelector(".form"),p=document.getElementById("get-images"),r=document.querySelector(".loader"),y=15,g=async()=>{const a=document.querySelector("[name='search']");if(a.value.trim()!==""){r.style.display="block";try{const t=await L(a.value.trim()),n=Math.ceil(t.totalHits/y);if(o.page>=n)return p.style.display="none",d(t.hits),parseInt(t.totalHits)<=0?(r.style.display="none",c("Sorry, there are no images matching your search query. Please try again!")):(r.style.display="none",c("We are sorry, but you've reached the end of search results."));p.style.display="inline-block",d(t.hits),r.style.display="none"}catch(t){r.style.display="none",console.error(t.message),c(t.message)}}else r.style.display="none",c("The field cannot be empty")};q.addEventListener("submit",a=>{a.preventDefault(),p.style.display="none",o.per_page=y,o.page=1,document.querySelector(".gallery").innerHTML="",g()});p.addEventListener("click",()=>{o.per_page=y,o.page++,document.querySelector(".gallery-link").getBoundingClientRect(),g(),setTimeout(()=>{window.scrollBy({top:850,behavior:"smooth"})},"500")});const c=a=>{v.error({message:a,position:"topRight",timeout:5e3})};
//# sourceMappingURL=commonHelpers.js.map
